import type { Project } from '../types';

// Fallback projects, used while Supabase is not configured or on error.
export const fallbackProjects: Project[] = [
    {
        id: '1',
        title: 'Photographer portfolio',
        description: 'Web project featuring a real estate photographer\'s portfolio. Showcases captivating property visuals, offers easy navigation, and provides contact details for collaborations.',
        tech: ['JS', 'HTML', 'CSS', 'React', 'TypeScript', 'Next', 'Tailwind'],
        images: ['/assets/photo_portfolio_1.webp', '/assets/photo_portfolio_2.webp', '/assets/photo_portfolio_3.webp', '/assets/photo_portfolio_4.webp'],
        link: 'https://photo.glafira.se/',
        important: null,
        sort_order: 1,
    },
    {
        id: '2',
        title: 'Drone Delight',
        description: 'Drone Delight is a modern food delivery app where users can create an account, log in, browse a wide selection of meals, add products to their cart, save favorites, and securely complete payments.',
        tech: ['JS', 'HTML', 'CSS', 'React', 'Node.js', 'Tailwind', 'react-router-dom', 'MongoDB'],
        images: ['/assets/drone-delight_1.webp', '/assets/drone-delight_3.webp', '/assets/drone-delight_4.webp', '/assets/drone-delight_6.webp'],
        link: 'https://drone-delight.netlify.app/',
        important: null,
        sort_order: 2,
    },
    {
        id: '3',
        title: 'SKILLUP',
        description: 'SKILLUP is a web app for interactive learning where users can enroll in courses, track progress, complete lessons, and earn digital certificates through a diverse course library and personal dashboards.',
        tech: ['Entity Framework', 'ASP.NET Identity', 'MongoDB', 'C#', 'Tailwind', 'React', 'TypeScript'],
        images: ['/assets/skillup_1.webp', '/assets/skillup_2.webp', '/assets/skillup_3.webp', '/assets/skillup_4.webp'],
        link: 'https://skillup-sysm8.netlify.app/',
        important: null,
        sort_order: 3,
    },
    {
        id: '4',
        title: 'WashOverflow',
        description: 'A car wash booking system that enables users to schedule car wash appointments. The system provides authentication, booking management, and an administrative interface to oversee operations.',
        tech: ['Razor Pages', 'Entity Framework', 'ASP.NET Identity', 'Azure SQL', 'C#', 'Bootstrap', 'Azure App Service'],
        images: ['/assets/washoverflow_1.webp', '/assets/washoverflow_2.webp', '/assets/washoverflow_3.webp'],
        link: 'https://washoverflow.azurewebsites.net/',
        important: null,
        sort_order: 4,
    },
    {
        id: '5',
        title: 'Sweet Shop',
        description: 'A responsive website for a candy store. Users can explore the product catalog, add products to the cart, and place orders. After placing an order, users receive a confirmation with the order number.',
        tech: ['JS', 'HTML', 'CSS', 'React', 'TypeScript', 'SASS', 'Bootstrap', 'react-router-dom', 'react-query', 'Vite'],
        images: ['/assets/sweet_1.webp', '/assets/sweet_2.webp', '/assets/sweet_3.webp', '/assets/sweet_4.webp'],
        link: 'https://sweet-shop-glafver.netlify.app/',
        important: null,
        sort_order: 5,
    },
    {
        id: '6',
        title: 'Videomaker',
        description: 'Videomaker app allows users to create video slideshows using uploaded photos. Users can customize slide order, duration, transitions, and add soundtracks. They can save, share, edit settings, or create new videos.',
        tech: ['JS', 'HTML', 'CSS', 'React', 'Node.js', 'Express.js', 'ffmpeg', 'ImageMagick', 'Bootstrap', 'Firebase', 'SASS', 'Docker', 'react-router-dom'],
        images: ['/assets/videomaker_1.webp', '/assets/videomaker_2.webp', '/assets/videomaker_3.webp'],
        link: 'https://videomaker.netlify.app/',
        important: null,
        sort_order: 6,
    },
    {
        id: '7',
        title: 'Tasty Malmö',
        description: 'Multi-tier access app for discovering restaurants in Malmö on a map and in a list. Users can explore the map, access detailed pages, see their location, find distances to restaurants, get route directions, and submit suggestions to admins.',
        tech: ['JS', 'HTML', 'CSS', 'React', 'Bootstrap', 'ReactQuery', 'Firebase', 'SASS', 'GoogleMapsAPI'],
        images: ['/assets/tasty_1.webp', '/assets/tasty_2.webp', '/assets/tasty_3.webp'],
        link: 'https://tasty-malmo.netlify.app/',
        important: null,
        sort_order: 7,
    },
    {
        id: '8',
        title: 'Almi - Uppstartslån',
        description: 'A web page for Almi\'s newest product, Uppstartslån. This one-page website serves as a guide to introduce customers to the features and benefits of Uppstartslån.',
        tech: ['JS', 'HTML', 'CSS'],
        images: ['/assets/almi_1.webp', '/assets/almi_2.webp', '/assets/almi_3.webp'],
        link: 'https://almi.netlify.app/',
        important: null,
        sort_order: 8,
    },
    {
        id: '9',
        title: 'Re-Yacht',
        description: 'A classic battleship game in real time for two players.',
        tech: ['JS', 'HTML', 'CSS', 'React', 'Socket.io', 'Node.js', 'Bootstrap', 'SASS', 'react-router-dom'],
        images: ['/assets/reyacht_1.webp', '/assets/reyacht_2.webp', '/assets/reyacht_3.webp', '/assets/reyacht_4.webp'],
        link: 'https://re-yacht.netlify.app/',
        important: 'If you want to try the game alone, open two tabs and log in as two players.',
        sort_order: 9,
    },
    {
        id: '10',
        title: 'Kill the virus',
        description: 'A two-player game where players compete to see who can kill the malicious virus faster.',
        tech: ['JS', 'HTML', 'CSS', 'React', 'Socket.io', 'Node.js'],
        images: ['/assets/virus_1.webp', '/assets/virus_2.webp', '/assets/virus_3.webp', '/assets/virus_4.webp'],
        link: 'https://kill-the-virus-ksa4rs3q2a-lm.a.run.app',
        important: 'If you want to try the game alone, open two tabs and log in as two players.',
        sort_order: 10,
    },
];

// Fallback site content (key -> text).
export const fallbackContent: Record<string, string> = {
    'hero.name': 'Glafira',
    'hero.role': 'Fullstack Developer',
    'hero.subtitle': 'with a passion for solving problems and high attention to visual details. My goal in work is to produce clean, understandable, and well-optimized code.',

    'projects.title': 'Have a look at my projects',
    'projects.subtitle': 'Here are some of my completed projects. While some may be simple, they represent my ongoing effort to grow professionally and continuously learn new skills.',

    'technologies.title': 'Tech Stack',

    'about.p1': 'Hi, my name is Glafira Veretennikova. Currently based in Malmö, Sweden, I relocated here six years ago from St. Petersburg, Russia. I am fluent in both Swedish and English.',
    'about.p2': 'I am a Fullstack Developer and my expertise includes C#, .NET, Blazor, React.js, TypeScript, and Node.js. I have experience working with Redux, Express.js, Socket.io, Tailwind, and Material UI, and writing tests with xUnit and Jest.',
    'about.p3': 'Easy-going by nature, I know how to listen and find the right approach to people and work. Skilled at collaborating in teams, I can both lead projects and work independently when needed.',
    'about.p4': 'Before transitioning into development, I spent over 15 years in administration and management. That experience sharpened my organizational skills, problem-solving, and customer focus — qualities I now bring to every project I build.',
    'about.p5': 'I am passionate about interior design and interior photography, working professionally as a freelance photographer. I also enjoy traveling and exploring different cultures to understand how people live, think and create their spaces.',

    'contact.title': 'Interested in working with me?',
    'contact.email': 'glafira.se@gmail.com',

    'social.linkedin': 'https://www.linkedin.com/in/glafver/',
    'social.facebook': 'https://www.facebook.com/glafver',
    'social.github': 'https://github.com/glafver',
    'social.instagram': 'https://www.instagram.com/glafver/',

    'cv.url': '/assets/Glafira_Veretennikova_fullstack_CV.pdf',

    'experience.title': 'Experience & Education',
    'education.title': 'Education',
    'work.title': 'Experience',
    'certificates.title': 'Certificates',
};
